### ISSUE TITLE
Fehler beim manuellen Erstellen der Übersetzungsgruppen

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-language-relations#12]
`Argument 1 passed to Hofff\Contao\LanguageRelations\DCA\GroupDCA::saveRoots() must be of the type int, string given, called in /htdocs/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php on line 3146`

**Comment by dmolineus** [comment]
Bereits behoben.
