### ISSUE TITLE
contao 4.9 Datenbank Migration nicht möglich

### ISSUE THREAD

**Issue by martinfrese** [hofff/contao-language-relations#14]
Bei einem Contao Update von 4.4 auf 4.9 bin ich bei der Datenbank Migration auf ein Problem gestoßen.

`[ERROR] Argument 1 passed to Contao\InstallationBundle\Database\Installer::execCommand() must be of the type string, int given, called in /[...]/vendor/contao/core-bundle/src/Command/MigrateCommand.php on line 387`

dd($hash) output:

` 0 => """
    CREATE OR REPLACE VIEW hofff_language_relations_page_item AS\n
    \n
    SELECT\n
        root_page.hofff_language_relations_group_id     AS group_id,\n
        root_page.id                                    AS root_page_id,\n
        page.id                                         AS page_id,\n
        page.id                                         AS item_id\n
    FROM\n
        tl_page\n
        AS page\n
    JOIN\n
        tl_page\n
        AS root_page\n
        ON root_page.id = page.hofff_root_page_id\n
        AND root_page.id != page.id\n
        AND root_page.type = 'root'
    """
`

Ich konnte das Problem lösen, indem dass ich unter src/Database/Installer.php die values mit Strings versehe:

`if(!isset($tables['hofff_language_relations_page_item'])) {
			$queries['ALTER_CHANGE']['**hofff_0**'] = StringUtil::tabsToSpaces($this->getItemView());
		}
		if(!isset($tables['hofff_language_relations_page_relation'])) {
			$queries['ALTER_CHANGE']['**hofff_1**'] = StringUtil::tabsToSpaces($this->getRelationView());
		}
		if(!isset($tables['hofff_language_relations_page_aggregate'])) {
			$queries['ALTER_CHANGE']['**hofff_2**'] = StringUtil::tabsToSpaces($this->getAggregateView());
		}
		if(!isset($tables['hofff_language_relations_page_tree'])) {
			$queries['ALTER_CHANGE']['**hofff_3**'] = StringUtil::tabsToSpaces($this->getTreeView());
		}`
		
Wäre es möglich diesen, oder einen anderen Fix einzubauen?
Ich stelle dazu noch einen PR.

**Comment by dmolineus** [comment]
Meanwhile fixed in the `develop` branch through 4f24b69c1c1c2994a9534bf62b966ed32c989fb2.
