### ISSUE TITLE
saving of relations in edit all is very slow

### ISSUE THREAD

**Issue by backbone87** [hofff/contao-language-relations#2]
ok das problem ist ein onsubmit callback vom contao core:
https://github.com/contao/core/blob/master/system/modules/core/dca/tl_page.php#L36

da der onsubmit callback für jeden bearbeiteten datensatz ausgeführt wird, wird auch die sitemap für jede bearbeitete seite ausgeführt. die sitemap generierung an sich ist rekursiv, was zu einer hohen laufzeitkomplexität führt.

ich habe ein ticket im core erstellt:
https://github.com/contao/core/issues/6830

**Comment by davidmaack** [comment]
Der Workaround funktioniert bei mir nicht, folgender Error wird geworfen:

`Fatal error: Cannot use object of type Closure as array in /path-to-contao/system/modules/hofff_language_relations/dca/tl_page.php on line 39

Call Stack
	Time	Memory	Function	Location
1	0.0001	283400	{main}( )	.../main.php:0
2	0.1327	2838376	Contao\BackendMain->run( )	.../main.php:20
3	0.1332	2981016	Contao\Backend->getBackendModule( )	.../BackendMain.php:131
4	0.1528	3058184	Contao\Controller::loadDataContainer( )	.../Backend.php:376
5	0.1531	3095440	Contao\DcaLoader->load( )	.../Controller.php:1300
6	0.1900	4196016	include( '/path-to-contao/system/modules/hofff_language_relations/dca/tl_page.php' )	.../DcaLoader.php:86`

Contao Version  3.5.9
PHP Version 5.6.14-0+deb8u1
hofff/contao-language-relations:	2.0.0-rc2

**Comment by frontendschlampe** [comment]
old ticket, if problem still exists, please reopen or make a new ticket
